package money.paybox.payboxsdk.api

object Urls {
    val BASE_URL = "https://api.paybox.money/"
    val FREEDOM_BASE_URL = "https://api.paybox.money/"
    val STATUS_URL = BASE_URL +"get_status.php"
    val INIT_PAYMENT_URL = BASE_URL + "init_payment.php"
    val REVOKE_URL = BASE_URL +"revoke.php"
    val CANCEL_URL = BASE_URL +"cancel.php"
    val CLEARING_URL = BASE_URL +"do_capture.php"
    val RECURRING_URL = BASE_URL +"make_recurring_payment.php"
    val SUCCESS_URL = BASE_URL +"success"
    val FAILURE_URL = BASE_URL +"failure"
    val CARDSTORAGE = "/cardstorage/"
    val CARD = "/card/"
    val LISTCARD_URL = "list"
    val CARDINITPAY = "init"
    val ADDCARD_URL = "add"
    val PAY = "pay"
    val REMOVECARD_URL = "remove"
    val DIRECT = "direct"
    fun CARD_PAY(merchant_id: String): String {
        return BASE_URL + "v1/merchant/" + merchant_id + CARD
    }
    fun CARD_MERCHANT(merchant_id: String): String {
        return BASE_URL + "v1/merchant/" + merchant_id + CARDSTORAGE
    }
    fun NONACCEPTANCE_DIRECT(merchant_id: String): String {
        return FREEDOM_BASE_URL + "v1/merchant/" + merchant_id + CARD + DIRECT
    }
}

object Params {
    val RECURRING_PROFILE_ID = "pg_recurring_profile_id"
    val CARD_CREATED_AT = "created_at"
    val RESPONSE = "response"
    val PAYMENT_FAILURE = "Не удалось оплатить"
    val UNKNOWN_ERROR = "Неизвестная ошибка"
    val CONNECTION_ERROR = "Ошибка подключения"
    val FORMAT_ERROR = "Неправильный формат ответа"
    val RECURRING_PROFILE_EXPIRY = "pg_recurring_profile_expiry_date"
    val CLEARING_AMOUNT = "pg_clearing_amount"
    val REFUND_AMOUNT = "pg_refund_amount"
    val ERROR_CODE = "pg_error_code"
    val ERROR_DESCRIPTION = "pg_error_description"
    val CAPTURED = "pg_captured"
    val CARD_PAN = "pg_card_pan"
    val CREATED_AT = "pg_create_date"
    val TRANSACTION_STATUS = "pg_transaction_status"
    val CAN_REJECT = "pg_can_reject"
    val REDIRECT_URL = "pg_redirect_url"
    val MERCHANT_ID = "pg_merchant_id"
    val SIG = "pg_sig"
    val SALT = "pg_salt"
    val STATUS = "pg_status"
    val CARD_ID = "pg_card_id"
    val CARD_HASH = "pg_card_hash"
    val TEST_MODE = "pg_testing_mode"
    val RECURRING_START = "pg_recurring_start"
    val AUTOCLEARING = "pg_auto_clearing"
    val REQUEST_METHOD = "pg_request_method"
    val CURRENCY = "pg_currency"
    val LIFETIME = "pg_lifetime"
    val ENCODING = "pg_encoding"
    val RECURRING_LIFETIME= "pg_recurring_lifetime"
    val PAYMENT_SYSTEM = "pg_payment_system"
    val SUCCESS_METHOD = "pg_success_url_method"
    val FAILURE_METHOD = "pg_failure_url_method"
    val SUCCESS_URL = "pg_success_url"
    val FAILURE_URL = "pg_failure_url"
    val BACK_LINK = "pg_back_link"
    val POST_LINK = "pg_post_link"
    val LANGUAGE = "pg_language"
    val USER_PHONE = "pg_user_phone"
    val USER_CONTACT_EMAIL = "pg_user_contact_email"
    val USER_EMAIL = "pg_user_email"
    val CAPTURE_URL = "pg_capture_url"
    val REFUND_URL = "pg_refund_url"
    val RESULT_URL = "pg_result_url"
    val CHECK_URL = "pg_check_url"
    val USER_ID = "pg_user_id"
    val ORDER_ID = "pg_order_id"
    val DESCRIPTION = "pg_description"
    val RECURRING_PROFILE = "pg_recurring_profile"
    val AMOUNT = "pg_amount"
    val PAYMENT_ID = "pg_payment_id"
    val TIMEOUT_AFTER_PAYMENT = "pg_timeout_after_payment"
    val PAYMENT_ROUTE = "pg_payment_route"
    val CARD_TOKEN = "pg_card_token"
}
